In [10]:
import numpy as np
import sys
import pandas as pd

### Linear Algebra

In [11]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])

In [12]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [13]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [14]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [15]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [29]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

#### Size of Objects in Memory

In [16]:
sys.getsizeof(1)

28

In [31]:
sys.getsizeof(10**100)

72

In [32]:
np.dtype(int).itemsize

4

In [33]:
np.dtype(float).itemsize

8

In [34]:
sys.getsizeof([1])

64

In [35]:
np.array([1]).nbytes

4

In [36]:
l = list(range(1000))

In [37]:
a = np.arange(1000)

In [38]:
%time np.sum(a**2)

CPU times: total: 0 ns
Wall time: 0 ns


332833500

In [39]:
%time sum([x**2 for x in l])

CPU times: total: 0 ns
Wall time: 0 ns


332833500