> Also called masks

In [1]:
import numpy as np

In [2]:
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

Quando temos um array, para exibir um determinado elemento utilizamos a[0], podemos utilizar um array como parametro para separar mais de um elemento

In [10]:
a[[1,-1]] # mostra os elementos nas posições a[1] e na última posição de a

array([1, 3])

In [16]:
a[[True, False, False, True]] # podemos passar booleanos como parametros 

array([0, 3])

Se utilizamos uma expressão booleana, é retornado um array booleno para cada elemento dizendo se a expressão é verdadeira ou falsa

In [11]:
a >= 2

array([False, False,  True,  True])

Quando utilizamos a expressão como parâmetro, nos é retornado os valores que são verdadeiros nela

In [12]:
a[a >=2 ]

array([2, 3])

In [13]:
a.mean()

1.5

In [20]:
a > a.mean()

array([False, False,  True,  True])

In [14]:
a[a> a.mean()]

array([2, 3])

In [19]:
a[~(a > a.mean())] # o ~ nega a expressão

array([0, 1])

In [21]:
a[(a==0) | (a==1)] # pode se utilizar or e and

array([0, 1])

In [22]:
a[(a<=2) & (a % 2 == 0)]

array([0, 2])

In [23]:
b = np.random.randint(100, size=(3,3))

In [24]:
b

array([[92, 38, 18],
       [78, 53, 34],
       [79, 18, 69]])

In [25]:
b[np.array([
    [True,True,False],
    [True,False,True],
    [False,True,False]
])]

array([92, 38, 78, 34, 18])

In [26]:
b < 30

array([[ True,  True, False],
       [ True,  True,  True],
       [ True, False,  True]])

In [28]:
b[b<30]

array([92, 38, 78, 53, 34, 79, 69])

##### Exemplo utilizando dois arrays

In [37]:
c = np.arange(6)
d = np.array([1,2,3,4,5,6])

In [38]:
c

array([0, 1, 2, 3, 4, 5])

In [39]:
d

array([1, 2, 3, 4, 5, 6])

In [40]:
d[c <= 2]

array([1, 2, 3])