In [2]:
import numpy as np
import sys

### Creating an array

In [3]:
a = np.array([1,2,3,4]) # Cria um array
print(a)

[1 2 3 4]


In [4]:
array = np.arange(5) # Cria um array com indíce 5
array

array([0, 1, 2, 3, 4])

In [5]:
a[0],a[1]

(1, 2)

### Slicing

In [6]:
a[:2] # Separa até o elemento 2
a[0:] # Separa do zero em diante
a[1:4] # Separa os elemetos do indíce 1 ao 4

array([2, 3, 4])

#### Types of arrays

In [7]:
a.dtype # Mostra o tipo do array

dtype('int32')

In [8]:
b = np.array([1,2,3,4,5], dtype= np.float64) # Definindo o tipo de um array
b.dtype

dtype('float64')

In [9]:
c = np.array(['a', 'b', 'c']) # Strings
c.dtype

dtype('<U1')

In [10]:
d = np.array([{'a':1}, sys]) # Objetos se pode armazenar, mas não há porquê, afinal é uma biblioteca de porcessamento numérico
d.dtype

dtype('O')

### Matrizes

#### Dimensões e Formatos

In [11]:
M = np.array([[1,2,3],   # Matriz 3x3
             [4,5,6],
             [7,8,9]])

In [12]:
M.shape # formato da matriz

(3, 3)

In [13]:
M.ndim #dimensão da matriz

2

In [14]:
M.size # tamanho da matriz

9

In [15]:
N = np.array([    # Matriz 2x2x3
    [
        [10,11,12],
        [13,14,15]
    ],
    [
        [16,17,18],
        [19,20,21]
    ]
])

In [16]:
N.dtype #Tipo da matriz

dtype('int32')

In [17]:
N.shape

(2, 2, 3)

In [18]:
N.ndim

3

In [19]:
N.size

12

In [20]:
type(N[0]) #Tipo da matriz N na posição 0

numpy.ndarray

In [21]:
type(N[0][0]) #Tipo da matriz N na posição 0 0

numpy.ndarray

In [22]:
type(N[0][0][0]) #Tipo da matriz N na posição 0 0 0

numpy.int32

#### Slicing Matrices

In [25]:
N[0] 

array([[10, 11, 12],
       [13, 14, 15]])

In [26]:
N[0][0]

array([10, 11, 12])

In [27]:
N[0][0][0]

10

In [29]:
N[0][1][1:3]

array([14, 15])

In [33]:
N[:][:2][:2]

array([[[10, 11, 12],
        [13, 14, 15]],

       [[16, 17, 18],
        [19, 20, 21]]])

### Summary Statistcs

In [45]:
s = np.array([1,2,3,4,5,6])

In [46]:
s.sum() # soma dos elementos

21

In [47]:
s.mean() # media dos elementos

3.5

In [48]:
s.std() # desvio padrão

1.707825127659933

In [49]:
r = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

In [50]:
r.sum()

36

In [51]:
r.mean()

4.5

In [52]:
r.std()

2.29128784747792

In [53]:
r.sum(axis=0) # soma das linhas

array([ 6,  8, 10, 12])

In [54]:
r.sum(axis=1) # soma das colunas

array([10, 26])