In [1]:
import numpy as np

In [4]:
a = np.arange(5)
a 

array([0, 1, 2, 3, 4])

## Operações com arrays do numpy

In [5]:
a + 10 # soma

array([10, 11, 12, 13, 14])

In [6]:
a * 10 # multiplicação

array([ 0, 10, 20, 30, 40])

In [8]:
a += 100 # altera dos valores de a

In [9]:
a

array([100, 101, 102, 103, 104])

In [10]:
l = [0,1,2,3]
[i*10 for i in l] # Com o numpy não precisamos do for

[0, 10, 20, 30]

In [12]:
l * 2 # sem o for ou o numpy só repitiramos o array

[0, 1, 2, 3, 0, 1, 2, 3]

#### Operaçaõ com dois arrays diferentes

In [15]:
b = np.arange(4)
c = np.array([10,11,12,13])

In [16]:
b + c

array([10, 12, 14, 16])

In [17]:
b * c

array([ 0, 11, 24, 39])